server:
  port: 8090

spring:
  application:
    name: board-back
  datasource:
    url: jdbc:mysql://localhost:3306/boarddb?createDatabaseIfNotExist=true
    username: root
    password: 12345
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      minimum-idle: 5
      maximum-pool-size: 10
      idle-timeout: 30000
      max-lifetime: 1800000
      connection-timeout: 30000
      auto-commit: true
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  thymeleaf:
    cache: false
    mode: HTML
    prefix: classpath:/templates/
    suffix: .html

# 키생성 : openssl rand -base64 32 
# 키(secret)값은 base64 32비트 문자열 또는 임의문자열(예 S3cr3tK3y!)을 설정해도 가능
# ms : 1000*60*60*24 = 24시간
jwt:
  secret: DdqOm0p+pbVNqhj12jafRAnzF62IyfOSFbzeIjTWvLY=
  expiration: 86400000  # (1일 = 1000 * 60 * 60 * 24)                                