server:
  port: 8090

spring:
  application:
    name: board-back
  datasource:
    url: jdbc:mysql://localhost:3306/boarddb?createDatabaseIfNotExist=true
    username: root
    password: 12345
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      minimum-idle: 5
      maximum-pool-size: 10
      idle-timeout: 30000
      max-lifetime: 1800000
      connection-timeout: 30000
      auto-commit: true
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 110MB

jwt:
  secret: c6da0f588b364ccd906e4cb00a6b5e7828a9cf54cbbfb6cdf7b687ecb26cb320        