server:
  port: 8090
  servlet:
    session:
      timeout: 30m  # 분단위 30m, 초단위 1800

spring:
  application:
    name: sec03_jwt
  datasource:
    url: jdbc:mysql://localhost:3306/secStudy?createDatabaseIfNotExist=true
    username: root
    password: 12345
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      minimum-idle: 5
      maximum-pool-size: 10
      idle-timeout: 30000
      max-lifetime: 1800000
      connection-timeout: 30000
      auto-commit: true
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 110MB
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

jwt:
  secret: jwts3cur!ty