# https://suddiyo.tistory.com/entry/Spring-Spring-Security-JWT-로그인-구현하기-2
server:
  port: 8090
  servlet:
    encoding:
      force-response: true
      charset: utf-8

spring:
  application:
    name: sec01_baic